/**
 * OGC API — Connected Systems (CSAPI) module.
 *
 * This barrel file re-exports all public CSAPI symbols accessible
 * via `@camptocamp/ogc-client/csapi`.
 *
 * @example
 * ```ts
 * import { CSAPIQueryBuilder } from '@camptocamp/ogc-client/csapi';
 * import type { System, Datastream } from '@camptocamp/ogc-client/csapi';
 * ```
 *
 * @module csapi
 */

// ── Factory Function ───────────────────────────────────────
export { createCSAPIBuilder } from './factory.js';

// ── Query Builder ──────────────────────────────────────────
export { default as CSAPIQueryBuilder } from './url_builder.js';

// ── Model Values ───────────────────────────────────────────
export {
  CSAPIResourceTypes,
  CommandStatusCodes,
  SystemTypeUris,
} from './model.js';

// ── Model Types ────────────────────────────────────────────
export type {
  CSAPIResourceType,
  CommandStatusCode,
  SystemTypeUri,
  TimeInterval,
  ResourceLink,
  CSAPIResourceRef,
  CsapiDateTimeParameter,
  QueryOptions as CSAPIQueryOptions,
  SystemQueryOptions,
  DeploymentQueryOptions,
  ProcedureQueryOptions,
  SamplingFeatureQueryOptions,
  PropertyQueryOptions,
  DatastreamQueryOptions,
  ObservationQueryOptions,
  ControlStreamQueryOptions,
  CommandQueryOptions,
  CommandStatusQueryOptions,
  System,
  Deployment,
  Procedure,
  SamplingFeature,
  Property,
  Datastream,
  Observation,
  ControlStream,
  Command,
  CommandStatus,
  FeatureCollection,
  ItemCollection,
  SystemCollection,
  DeploymentCollection,
  ProcedureCollection,
  SamplingFeatureCollection,
  PropertyCollection,
  DatastreamCollection,
  ObservationCollection,
  ControlStreamCollection,
  CommandCollection,
  CommandStatusCollection,
  DatastreamSchemaResponse,
  ControlStreamSchemaResponse,
} from './model.js';

// ── Format Handler Values ──────────────────────────────────
export {
  SOSA_NS,
  SSN_NS,
  SENSORML_NS,
  isCSAPIFeature,
  getCSAPIResourceType,
  parseValidTime,
  isValidUri,
  extractCSAPIFeature,
  parseSensorML30,
  parseSWEComponent,
  parseVector,
  parseMatrix,
  parseDataChoice,
  parseGeometry,
  detectEncoding,
  validateAgainstSchema,
  CSAPI_CONTENT_TYPES,
  getContentTypeForResource,
  parseProperty,
  parseDatastream,
  parseObservation,
  parseControlStream,
  parseCommand,
  parseCommandStatus,
  normalizeStatusCode,
  parseDatastreamSchemaResponse,
  parseControlStreamSchemaResponse,
} from './formats/index.js';

// ── Format Handler Types ───────────────────────────────────
export type { CSAPIResourceTypeName } from './formats/index.js';
export type {
  SensorMLProcess,
  SensorMLProcessType,
  PhysicalSystem,
  PhysicalComponent,
  SimpleProcess,
  AggregateProcess,
  DescribedObject,
  AbstractProcess,
  AbstractPhysicalProcess,
  CapabilityList,
  CharacteristicList,
  Term,
  ComponentList,
  ComponentEntry,
  ConnectionList,
  Connection,
  Settings,
  Link as SensorMLLink,
  ResponsibleParty,
  InputList,
  OutputList,
  ParameterList,
  IOComponentChoice,
  Mode,
  Event,
  Position,
  Pose,
  GeoJsonPoint,
  Document as SensorMLDocument,
  FeatureList,
  LegalConstraint,
  SecurityConstraint,
  ContactInfo,
  ContactLink,
  ObservableProperty,
  AnyProperty,
  ProcessMethod,
  SpatialFrame,
  TemporalFrame,
  TimePeriod,
  TimeInstant,
  TimeInstantOrPeriod,
  ComponentLink,
  SettingValue,
  SettingArrayValue,
  SettingMode,
  SetConstraint,
  SettingStatus,
  FrameAxis,
} from './formats/index.js';
export type {
  AnyComponent,
  AnyScalarComponent,
  AnySimpleComponent,
  DataRecord,
  Vector,
  Matrix,
  DataChoice,
  DataArray,
  SweGeometry,
  SweBoolean,
  SweCount,
  SweQuantity,
  SweText,
  SweCategory,
  SweTime,
  SweCountRange,
  SweQuantityRange,
  SweTimeRange,
  SweCategoryRange,
  DataEncoding,
  TextEncoding,
  JSONEncoding,
  BinaryEncoding,
  XMLEncoding,
  ValidationResult,
  UnitOfMeasure,
  AllowedValues,
  AllowedTokens,
  AllowedTimes,
  DataField,
  TypedDataField,
  ElementCount,
  EncodedValues,
  AssociationAttributeGroup,
  NilValue,
  NilValuesNumber,
  NilValuesInteger,
  NilValuesText,
  NilValuesTime,
  NumberOrSpecial,
  DateTimeNumberOrSpecial,
  GeometryConstraint,
  GeometryType,
  GeoJsonGeometry,
  BinaryMember,
  BinaryComponent,
  BinaryBlock,
  ValidationError,
} from './formats/index.js';
