export { default as WfsEndpoint } from './wfs/endpoint.js';
export type {
  WfsVersion,
  WfsFeatureWithProps,
  WfsFeatureTypeSummary,
  WfsFeatureTypeBrief,
  FeatureGeometryType,
  FeaturePropertyType,
  WfsFeatureTypeFull,
  WfsFeatureTypePropDetails,
  WfsFeatureTypePropsDetails,
  WfsFeatureTypeUniqueValue,
  WfsGetFeatureOptions,
} from './wfs/model.js';
export { default as WmsEndpoint } from './wms/endpoint.js';
export type {
  WmsLayerFull,
  WmsVersion,
  WmsLayerSummary,
  WmsLayerAttribution,
  WmsLayerDescription,
} from './wms/model.js';
export { default as WmtsEndpoint } from './wmts/endpoint.js';
export type {
  WmtsLayerDimensionValue,
  WmtsLayerResourceLink,
  WmtsEndpointInfo,
  WmtsLayer,
  WmtsMatrixSet,
} from './wmts/model.js';
export type {
  Address,
  Contact,
  Provider,
  LayerStyle,
  BoundingBox,
  MetadataURL,
  FetchOptions,
  GenericEndpointInfo,
  MimeType,
  CrsCode,
  DateTimeParameter,
} from './shared/models.js';
export { default as OgcApiEndpoint } from './ogc-api/endpoint.js';
export * from './ogc-api/model.js';
export { default as CSAPIQueryBuilder } from './ogc-api/csapi/url_builder.js';
export {
  CSAPIResourceTypes,
  CommandStatusCodes,
  SystemTypeUris,
} from './ogc-api/csapi/model.js';
export type {
  CSAPIResourceType,
  CommandStatusCode,
  SystemTypeUri,
  TimeInterval,
  ResourceLink,
  CSAPIResourceRef,
  CsapiDateTimeParameter,
  QueryOptions as CSAPIQueryOptions,
  SystemQueryOptions,
  DeploymentQueryOptions,
  ProcedureQueryOptions,
  SamplingFeatureQueryOptions,
  PropertyQueryOptions,
  DatastreamQueryOptions,
  ObservationQueryOptions,
  ControlStreamQueryOptions,
  CommandQueryOptions,
  CommandStatusQueryOptions,
  System,
  Deployment,
  Procedure,
  SamplingFeature,
  Property,
  Datastream,
  Observation,
  ControlStream,
  Command,
  CommandStatus,
  FeatureCollection,
  ItemCollection,
  SystemCollection,
  DeploymentCollection,
  ProcedureCollection,
  SamplingFeatureCollection,
  PropertyCollection,
  DatastreamCollection,
  ObservationCollection,
  ControlStreamCollection,
  CommandCollection,
  CommandStatusCollection,
} from './ogc-api/csapi/model.js';
export type {
  DatastreamSchemaResponse,
  ControlStreamSchemaResponse,
} from './ogc-api/csapi/model.js';
export {
  SOSA_NS,
  SSN_NS,
  SENSORML_NS,
  isCSAPIFeature,
  getCSAPIResourceType,
  parseValidTime,
  isValidUri,
  extractCSAPIFeature,
  parseSensorML30,
  parseSWEComponent,
  parseVector,
  parseMatrix,
  parseDataChoice,
  parseGeometry,
  detectEncoding,
  validateAgainstSchema,
  CSAPI_CONTENT_TYPES,
  getContentTypeForResource,
  parseProperty,
  parseDatastream,
  parseObservation,
  parseControlStream,
  parseCommand,
  parseCommandStatus,
  normalizeStatusCode,
  parseDatastreamSchemaResponse,
  parseControlStreamSchemaResponse,
} from './ogc-api/csapi/formats/index.js';
export type { CSAPIResourceTypeName } from './ogc-api/csapi/formats/index.js';
export type {
  SensorMLProcess,
  SensorMLProcessType,
  PhysicalSystem,
  PhysicalComponent,
  SimpleProcess,
  AggregateProcess,
  DescribedObject,
  AbstractProcess,
  AbstractPhysicalProcess,
  CapabilityList,
  CharacteristicList,
  Term,
  ComponentList,
  ComponentEntry,
  ConnectionList,
  Connection,
  Settings,
  Link as SensorMLLink,
  ResponsibleParty,
  InputList,
  OutputList,
  ParameterList,
  IOComponentChoice,
  Mode,
  Event,
  Position,
  Pose,
  GeoJsonPoint,
  Document as SensorMLDocument,
  FeatureList,
  LegalConstraint,
  SecurityConstraint,
  ContactInfo,
  ContactLink,
  ObservableProperty,
  AnyProperty,
  ProcessMethod,
  SpatialFrame,
  TemporalFrame,
  TimePeriod,
  TimeInstant,
  TimeInstantOrPeriod,
  ComponentLink,
  SettingValue,
  SettingArrayValue,
  SettingMode,
  SetConstraint,
  SettingStatus,
  FrameAxis,
} from './ogc-api/csapi/formats/index.js';
export type {
  AnyComponent,
  AnyScalarComponent,
  AnySimpleComponent,
  DataRecord,
  Vector,
  Matrix,
  DataChoice,
  DataArray,
  SweGeometry,
  SweBoolean,
  SweCount,
  SweQuantity,
  SweText,
  SweCategory,
  SweTime,
  SweCountRange,
  SweQuantityRange,
  SweTimeRange,
  SweCategoryRange,
  DataEncoding,
  TextEncoding,
  JSONEncoding,
  BinaryEncoding,
  XMLEncoding,
  ValidationResult,
  UnitOfMeasure,
  AllowedValues,
  AllowedTokens,
  AllowedTimes,
  DataField,
  TypedDataField,
  ElementCount,
  EncodedValues,
  AssociationAttributeGroup,
  NilValue,
  NilValuesNumber,
  NilValuesInteger,
  NilValuesText,
  NilValuesTime,
  NumberOrSpecial,
  DateTimeNumberOrSpecial,
  GeometryConstraint,
  GeometryType,
  GeoJsonGeometry,
  BinaryMember,
  BinaryComponent,
  BinaryBlock,
  ValidationError,
} from './ogc-api/csapi/formats/index.js';
export { default as TmsEndpoint } from './tms/endpoint.js';
export * from './tms/model.js';
export { default as StacEndpoint } from './stac/endpoint.js';
export * from './stac/model.js';
export type {
  GetCollectionItemsOptions,
  StacEndpointInfo,
  StacItemsDocument,
} from './stac/index.js';

export { useCache, clearCache } from './shared/cache.js';
export {
  sharedFetch,
  setFetchOptions,
  resetFetchOptions,
} from './shared/http-utils.js';
export {
  check,
  ServiceExceptionError,
  EndpointError,
} from './shared/errors.js';

export { enableFallbackWithoutWorker } from './worker/index.js';
import './worker-fallback/index.js';
